### ISSUE TITLE
Add error rebounding

### ISSUE THREAD

**Issue by kerriannercrawford** [blendededge/sftp-component-oih#37]
It is possible for the SFTP server to time out/throw an error. The component should be able to handle these errors gracefully and provide an option to push the error to another step in the flow.

**Comment by ryanlunka** [comment]
Two good examples are:
`connect->getConnection: Timed out while waiting for handshake`
`connect->getConnection: Remote host has reset the connection: read ECONNRESET`

These are logged when the SFTP component fails to connect to an SFTP server and orchestrated action may need to be taken, such as messaging back to the requesting system.
