### ISSUE TITLE
Include Username When Private Key From Secret

### ISSUE THREAD

**Issue by ryanlunka** [blendededge/sftp-component-oih#52]
I think we want to make sure this uses the `username` if set in addition to the `privateKey` it pulls from the secret. I believe, right now this only uses the `privateKey` if you give it a secret.

https://github.com/blendededge/sftp-component-oih/blob/e13fa8155977f2a539bfa24907d5904d6729473d/lib/Sftp.js#L39C16-L39C16

Compare this to the following line later in this `else-if` where it uses `privateKey` and `username`.

https://github.com/blendededge/sftp-component-oih/blob/e13fa8155977f2a539bfa24907d5904d6729473d/lib/Sftp.js#L47

**Comment by winklerj** [comment]
Fixed in #53
